---
title: "Panel Ciudadanía Escolar"
---

# Cómo y dónde subir datos

La mayoría de las buenas experiencias presentadas sobre el almacenamiento de datos requieren para poder subir los datos de la investigación el estar afiliado a una institución asociada o el pagar por dicho servicio. Un caso contrario es el de los repositorios MOVID y el laboratorio de acceso a la justicia, pues estos almacenamientos de datos y productos de investigación utilizaron plataformas de ciencia abierta, como lo son Git Hub y OSF. 

Entre las distintas páginas web que prestan servicios similares se puede decir que OSF es una de las más completas, en tanto permite hacer identificadores doi para cumplir con los criterios FAIR, permite generar metadatos de forma sencilla, puede adaptarse a distintas necesidades individuales o institucionales, además de poseer una diversidad de herramientas para registrar las distintas etapas del proceso de investigación. Otra ventaja considerable de OSF es que como se sugiere en libro de @corti_Managing_2019,  permite sincronizar distintos repositorios, lo cual junto con dejar versiones en servidores locales, puede ayudar a preservar los datos y productos de la investigación incluso después de que la plataforma esté operando.


## OSF 

La plataforma web OSF permite un espacio de registro para los distintos procesos de la investigación. Un usuario normal de esta página puede crear repositorio denominado proyecto, el cual puede contener a su vez componentes que pueden ser investigaciones o datos específicos dentro del proyecto. Se pueden crear más componentes de estos tipos dentro de los componentes del proyecto. Esta estructura permite almacenar conjuntamente trabajos relacionados.

La página promueve que se registren productos de la investigación de las distintas etapas del proceso. En primer lugar posee un espacio para los "pre-registros" que son un documento en el cual se expone brevemente el diseño de la investigación, las hipótesis y la metodología, lo cual aumenta la rigurosidad de las investigación.
 

# Consejos para la Apertura de Datos de Investigación Social (CADIS)

## __Documentación:__

* Se deben recopilar y producir los siguientes materiales con el objetivo de que los usuarios de la base de datos cuenten con información suficiente para utilizarla correctamente. Los siguientes documentos deben ser subidos en PDF y .txt con codificación utf8. 
    
    + Cuestionario
    + Consentimiento informado
    + Ficha técnica
    + Manual de usuario
    + Descriptivos (Optativo)
    + Publicaciones asociadas a los datos (Optativo)
    + Descripción e información detallada para metadatos. 
    
## __Curatoría:__ 


### Cuantitativo

* Estructurar los datos

    + Ordenar de modo tal que columnas sean variables y las filas sujetas.
    + Las categorías de los nombres no pueden estar en la primera fila, sino en formatos estructurados como etiquetas.
    + Revise la codificación. es decir la coherencia entre los valores las respuestas de las personas y el cuestionario.
    
* Codificar de forma adecuada y unica los casos perdidos. 

    + No sabe (-999)
    + No contesta (-888)
    + Marca más de una opcion cuando no corresponde (-777)
    
* Agregar información para identificar variables y alternativas. 

    + Asignar nombres a las variables que reflejen el contenido brevemente. Deben ser alfanuméricos en minúscula (sin símbolos ; , : “ $ @), remplazando espacios por guionbajo. En caso de encuestas longitudinales mantener el nombre de las variables en las distintas olas y señalar ola (p. ej. conf_partidos_o1,conf_partidos_o2,conf_partidos_o3).
    + Agregar etiquetas a las variables que incluyan información detallada de la pregunta.
    + Agregar etiquetas a las categorías de respuesta. 
    
* Resguardar la identidad de los encuestados
  
  + Eliminar aquellas variables que puedan ayudar a identificar a los encuestados, tales como direcciones, teléfonos, nombres, o direcciones IP, rut o mrut. Utilizar solo identificadores aleatorios y arbitrarios.

* Transformar la base a distintos formatos
  
  + SPSS (.sav)
  + STATA (.dta)
  + SAS () , Texto (.csv), R (.RData).
 
### Cualitativo

Para preparar y ordenar los datos cualitativos se requiere cumplir tanto con aspectos de contenido como de forma.

En términos de contenido es importante archivar toda la documentación relacionada con el proceso de la investigación. Un elemento fundamental es el almacenamiento de las transcripciones de las entrevistas, grupos focales o grupos de discusión. En consideración de que al estar presente en la entrevista se cuenta con una mayor información que solo leyendo su transcripción cualquier anotación que dé cuenta del ambiente anímico de la entrevista o del gesto que acompaña alguna frase es bienvenida. También es importante subir la pauta de la entrevista si es que existe. Asimismo, aquellos investigadores que hacen un análisis mediante codificación tienen registro del proceso por el cual llegaron a los códigos utilizados para la categorización de la información. Además, esto puede ser complementado con la descripción de las discusiones que surgieron entre el equipo de investigación para establecer tales códigos y el esquema de análisis [@kapiszewski_Transparency_2019]. Igualmente, necesario es cambiar el texto lo que sea necesario para que los sujetos de investigación no puedan ser identificados. también es conveniente compartir el cuaderno de campo de la investigación. 

Esta información bien almacenada no solo ayudara a las ciencias sociales por su apoyo con información a otros investigadores, sino que conjuntamente es un gran aporte a la formación de los estudiantes sobre como investigar cualitativamente, pues estos materiales permiten una aproximación más concreta al proceso de investigación cualitativo @bishop_Revisiting_2017.


En términos de formato es necesario seguir dos principios que en ocasiones pueden ser contrapuestos. En primer lugar, es necesario almacenar la información en formatos que sean ampliamente compartidos y utilizados en el campo de investigación. En segundo lugar, es necesario guardar los datos en formatos libres, que si bien no siempre son utilizados, a diferencia de los formatos propietarios pueden ser abiertos por personas de distintos países y hacen los datos perdurables incluso después de que el formato ampliamente sea desechado. Para cumplir con ambas exigencias se recomienda subir los documentos en distintos formatos. 


Formatos para documentos de texto:

* .pdf

* .txt

Formatos para grabaciones: 

* .mp3

* .ogg

Formatos para imágenes:

* .png

* .jpg


## __Almacenamiento.__

* Subir los datos originales, los datos etiquetados y la documentación [Open Science Framework](https://osf.io/)

  + Indicar que el contenido del proyecto son datos. 
  + Agregar una descripción suficiente. 
  + Indicar palabras clave. Incluir el termino "data". 
  + Para mayor información sobre este proceso visite el siguiente [tutorial]() 

* Resguardar los datos en algun servidor local de confianza. 
  
  + Evaluar la posibilidad de almacenar en servidores de univercidades y/o bibliotecas. Es importante resguardar los datos despues de su curatoria.
  
* Crear en osf:
  
  + Licencia Creativ Commonts (CC-0)
  + Crear DOI
  + señalar el tipo de documento.
  
  
---

    