---
title: "Sobre el almacenamiento abierto de datos"
subtitle: "Propuesta para la apertura de datos de investigación social"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
fontsize: 14pt
# mainfont: Palatino
# monofont: "Source Code Pro"
# monofontoptions: "Scale=0.8"
bibliography: [almacenamiento.bib]
biblio-style: apalike
link-citations: yes
---


# Presentación 


Actualmente las investigaciones sociales producen una gran cantidad de información como transcripciones de entrevistas y bases de datos de encuestas, que implican una gran inversión de recursos humanos y económicos financiado generalmente con fondos públicos. No obstante, la información producida no siempre es aprovechada por el público, ni por todos los investigadores que podrían desarrollar proyectos con estos materiales. Esta información y datos tampoco son preparados para su preservación, en miras de resguardar el conocimiento producido y almacenarlo en espacios que puedan perdurar en el tiempo y servir a las siguientes generaciones. Para que estas bases sean preservadas y utilizadas, es necesario que se encuentren a libre disposición de los investigadores y en repositorios múltiples que permitan su preservación. Esta apertura puede hacerse después de que el equipo de investigación que produjo el material haya cumplido sus objetivos con los datos, fomentando una ciencia colaborativa y mayor provecho de los trabajos de investigación.  [@vandijk_Open_2020]. 

La necesidad de una ciencia abierta que sea transparente con la producción de su información ha sido relevada por la Organización para la Cooperación y el Desarrollo Económicos [@ocde_Open_2020]. Más aun, generar políticas para adoptar las practicas de ciencia abierta en la investigación financiada públicamente es una exigencia para mantenerse en la organización. En Chile, la Agencia Nacional de Investigación y Desarrollo (ANID) del ministerio de ciencias ha generado una consulta pública sobre la temática y señalaron posteriormente que el cumplimiento de los principios de ciencia abierta será una condición para las investigaciones financiadas, para garantizar el acceso a la información científica por parte de la ciudadanía [@anid_Con_2020]. Por ello, la apertura de los datos ya no solo es una recomendación internacional, sino que es actualmente una necesidad para los investigadores de ciencias sociales financiados públicamente. 


Además de las exigencias de los financiadores, existen distintas razones para abrir los datos y la información producida, entre ellas algunas razones éticas, otras científicas y algunos incentivos personales.

En términos éticos, teniendo en consideración que los datos suelen ser producidas por instituciones o investigadores financiados con fondos públicos, los ciudadanos tienen el derecho de acceder a los productos de la investigación [@bueno_What_2017]. Además, considerando que los recursos públicos asignados a investigación son escasos, la apertura de las bases de datos permite su reutilización y por ello ahorra recursos en la construcción de bases de datos, fomentando la eficiencia fiscal [@gomez_Datos_2016]. Igualmente, la apertura de los datos fomenta la ética investigativa y la confiabilidad, reduce el fraude y aumenta el valor de la sociología para los políticos y el público [@breznau_Future_2019]. 

En términos academicos y científicos, dejar la base de datos a libre disposición permite hacer evaluaciones sobre la rigurosidad de los resultados mediante la reproducibilidad, mejorando la calidad y la confianza en la ciencia según señala la Organización de las Naciones Unidas para la Educación, la ciencia y la cultura [@unesco_Que_2020], mientras fomenta que más investigadores utilicen los datos y produzcan información (Whyte y Pryor, 2011), aumentando la colaboración y con ello la innovación científica segun señala el Foro Abierto de Ciencias Latinoamerica y el Caribe CILIAC [@ramirez_Ciencia_2019]. Además, poder acceder a los productos, procesos y discusiones propias de la investigación cualitativa, puede ayudar pedagógicamente a la formación universitaria, dando una idea más clara de lo que  implica una investigación[@bishop_Revisiting_2017]

Por último, en relación a los incentivos personales, entregar los materiales producidos a libre disposición del público con identificadores que permiten citar su trabajo y las investigaciones asociadas, fomenta un mayor impacto y visibilidad de las investigaciones, en concreto, como señala la investigación de  @piwowar_Data_2013 una investigación que comparte sus datos puede ser citada en un 30% más. Si bien, a veces se puede sentir que el trabajo o el material no es tan bueno como para compartirlo se debe pensar que el compartir el diseño de investigación, las hipótesis y los datos puede fomentar comentarios constructivos respecto a la dirección de la investigación, ayudando a mejorar la calidad del material [@sharan_Ten_2020]

Pese a las ventajas otorgadas por la apertura de los datos, los investigadores poseen reticencias a la hora de publicar abiertamente "sus" datos [@ferguson_How_2014; @sharan_Ten_2020] entre las cuales destacan: 
  
   * Miedo a las consecuencias negativas (mal uso, consecuencias legales o comerciales, entre otros).
  
   * Temor a la falta del reconocimiento debido de su trabajo.
  
   * Disgusto frente a la carga de trabajo que implica preparar los datos para su publicación. 
  
   * Desconocimiento de cómo y dónde compartir los datos.


En miras de las compresibles dudas de los investigadores señaladas por @ferguson_How_2014 y @sharan_Ten_2020, el presente documento busca facilitar la introducción al almacenamiento y publicación de datos. Se busca entregar información para resolver los cuatro puntos señalados, dando cuenta de lo que debe hacerse para disminuir los riesgos, fomentar el reconocimiento del trabajo propio, facilitar el mejoramiento de la calidad de los datos y entregar información sobre dónde y cómo compartir los datos. 

Para ello, este documento ofrece una propuesta de pasos a seguir para mejorar la calidad de los materiales de investigación producidos antes de publicarla en la web. Esta propuesta busca conciliar los estándares considerados óptimos en materia de almacenamiento y preservación de datos, con la realidad de las capacidades y herramientas de los investigadores chilenos en ciencias sociales. Dicho de otro modo, proponemos una lista de tareas a realizar para cumplir con los _mínimos_ necesarios para mejorar la calidad de los datos a publicar. 

El documento parte presentando conceptos básicos de almacenamiento, posteriormente expone estándares comunes a nivel internacional y algunas propuestas para mejorar la calidad de los datos. Finalmente ofrece un conjunto de Consejos para la Apertura de Datos de Investigación Social (CADIS), que responden al cómo y dónde publicar los datos para seguir dichos estándares y propuestas. 





```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
<!--stackedit_data:
eyJoaXN0b3J5IjpbLTkwNjg2NzgxMiwtMTU3NTk5MjldfQ==
-->
